export async function llenadoTablas(tablaCategoria,tablaSubcategoria, tablaUsuario){
    //Inyección de datos
    tablaCategoria.bulkCreate([
        { nombre: 'Tecnologías' },
        { nombre: 'Electrodomésticos' },
        { nombre: 'Decohogar' },
        { nombre: 'Ropa, Vestuario y Calzado' },
        { nombre: 'Salud y Belleza' },
        { nombre: 'Deportes y Aire Libres' },
        { nombre: 'Supermercados' },
        { nombre: 'Construcción y Ferreterías' },
        { nombre: 'Bebés y Niños Pequeños' },
        { nombre: 'Juguetería y Juegos de Mesas' },
        { nombre: 'Productos para Mascotas' },
        { nombre: 'Instrumentos Musicales' },
        { nombre: 'Vehículos y Recambios' }
    ])

    tablaSubcategoria.bulkCreate([
        { nombre: 'Smartphones', idcategoria_categoria: 1 },
        { nombre: 'Carcasas', idcategoria_categoria: 1 },
        { nombre: 'Soporte y Accesorios de Celulares', idcategoria_categoria: 1 },
        { nombre: 'Láminas Protectoras', idcategoria_categoria: 1 },
        { nombre: 'Teléfonos Fijos', idcategoria_categoria: 1 },
        { nombre: 'Notebooks, Tablets y Monitores', idcategoria_categoria: 1 },
        { nombre: 'Notebooks y Macbooks', idcategoria_categoria: 1 },
        { nombre: 'Tablets, iPads y Kindles', idcategoria_categoria: 1 },
        { nombre: 'Monitores', idcategoria_categoria: 1 },
        { nombre: 'Accesorios para Monitores', idcategoria_categoria: 1 },
        { nombre: 'Accesorios para Tablet', idcategoria_categoria: 1 },
        { nombre: 'Fundas para Notebook', idcategoria_categoria: 1 },
        { nombre: 'Smart TV', idcategoria_categoria: 1 },
        { nombre: 'Streaming', idcategoria_categoria: 1 },
        { nombre: 'Proyectores', idcategoria_categoria: 1 },
        { nombre: 'Soportes de TV y de Proyectores', idcategoria_categoria: 1 },
        { nombre: 'Controles Remoto y Antenas', idcategoria_categoria: 1 },
        { nombre: 'Audífonos', idcategoria_categoria: 1 },
        { nombre: 'Parlantes y Minicomponentes', idcategoria_categoria: 1 },
        { nombre: 'Soundbar y Subwoofers', idcategoria_categoria: 1 },
        { nombre: 'DJ y Audio Especializado', idcategoria_categoria: 1 },
        { nombre: 'Amplificadores de Sonido', idcategoria_categoria: 1 },
        { nombre: 'Micrófonos', idcategoria_categoria: 1 },
        { nombre: 'Radios y Walkie Talkie', idcategoria_categoria: 1 },
        { nombre: 'Smartwach y Apple Watch', idcategoria_categoria: 1 },
        { nombre: 'Smartbands', idcategoria_categoria: 1 },
        { nombre: 'Correas, Protectores y Accesorios', idcategoria_categoria: 1 },
        { nombre: 'Consolas', idcategoria_categoria: 1 },
        { nombre: 'Juegos para Consolas', idcategoria_categoria: 1 },
        { nombre: 'Controles y Accesorios', idcategoria_categoria: 1 },
        { nombre: 'Iluminación Inteligente', idcategoria_categoria: 1 },
        { nombre: 'Robots de Aseo y Limpieza', idcategoria_categoria: 1 },
        { nombre: 'Asistentes de Voz', idcategoria_categoria: 1 },
        { nombre: 'Enchufes e Interruptores', idcategoria_categoria: 1 },
        { nombre: 'Productos para Mascotas', idcategoria_categoria: 1 },
        { nombre: 'Cámaras y Kit de Seguridad', idcategoria_categoria: 1 },
        { nombre: 'Cerraduras y Sensores', idcategoria_categoria: 1 },
        { nombre: 'Mouse y Teclados', idcategoria_categoria: 1 },
        { nombre: 'Mousepads', idcategoria_categoria: 1 },
        { nombre: 'Ventiladores, Bases y Soportes', idcategoria_categoria: 1 },
        { nombre: 'Impresoras y suministros', idcategoria_categoria: 1 },
        { nombre: 'Routers y Repetidores Wifi', idcategoria_categoria: 1 },
        { nombre: 'Cargadores y UPS', idcategoria_categoria: 1 },
        { nombre: 'Adaptadores y Cables', idcategoria_categoria: 1 },
        { nombre: 'Antivirus y Softwares', idcategoria_categoria: 1 },
        { nombre: 'Disco Duro, Pendrive y MicroSD', idcategoria_categoria: 1 }
    ]);

    tablaSubcategoria.bulkCreate([
        { nombre: 'Freidoras de Aire', idcategoria_categoria: 2 },
        { nombre: 'Cafeteras', idcategoria_categoria: 2 },
        { nombre: 'Sandwicheras y Wafleras', idcategoria_categoria: 2 },
        { nombre: 'Parrillas y Planchas', idcategoria_categoria: 2 },
        { nombre: 'Batidoras y Licuadoras', idcategoria_categoria: 2 },
        { nombre: 'Exprimidores', idcategoria_categoria: 2 },
        { nombre: 'Hervidores y Teteras', idcategoria_categoria: 2 },
        { nombre: 'Selladoras al Vacío', idcategoria_categoria: 2 },
        { nombre: 'Yogurteras', idcategoria_categoria: 2 },
        { nombre: 'Máquinas de Palomitas', idcategoria_categoria: 2 },
        { nombre: 'Tostadores', idcategoria_categoria: 2 },
        { nombre: 'Refrigeradores', idcategoria_categoria: 2 },
        { nombre: 'Cocina y Hornos', idcategoria_categoria: 2 },
        { nombre: 'Cocinas y Encimeras', idcategoria_categoria: 2 },
        { nombre: 'Hornos Empotrables y Eléctrico', idcategoria_categoria: 2 },
        { nombre: 'Hornos Microondas', idcategoria_categoria: 2 },
        { nombre: 'Campanas y Extractores', idcategoria_categoria: 2 },
        { nombre: 'Ollas y Sartenes', idcategoria_categoria: 2 },
        { nombre: 'Juego de Loza', idcategoria_categoria: 2 },
        { nombre: 'Vasos y Copas', idcategoria_categoria: 2 },
        { nombre: 'Cubiertos y Utensilios de Mesa', idcategoria_categoria: 2 },
        { nombre: 'Lavadoras', idcategoria_categoria: 2 },
        { nombre: 'Secadoras', idcategoria_categoria: 2 },
        { nombre: 'Lavadora+Secadora', idcategoria_categoria: 2 },
        { nombre: 'Lavavajillas', idcategoria_categoria: 2 },
        { nombre: 'Planchas', idcategoria_categoria: 2 },
        { nombre: 'Estufas', idcategoria_categoria: 2 },
        { nombre: 'Calefactores', idcategoria_categoria: 2 },
        { nombre: 'Calientacamas', idcategoria_categoria: 2 },
        { nombre: 'Aire Acondicionado', idcategoria_categoria: 2 },
        { nombre: 'Ventiladores', idcategoria_categoria: 2 },
        { nombre: 'Calefont', idcategoria_categoria: 2 },
        { nombre: 'Aspiradoras', idcategoria_categoria: 2 },
        { nombre: 'Máquinas de Coser', idcategoria_categoria: 2 },
    ]);

    tablaSubcategoria.bulkCreate([
        { nombre: 'Closet, Veladores y Armarios', idcategoria_categoria: 3 },
        { nombre: 'Racks y Estantes', idcategoria_categoria: 3 },
        { nombre: 'Muebles de Oficina y Escritorios', idcategoria_categoria: 3 },
        { nombre: 'Muebles de Cocina', idcategoria_categoria: 3 },
        { nombre: 'Muebles de Baño', idcategoria_categoria: 3 },
        { nombre: 'Mobiliario para bebés y niños pequeños', idcategoria_categoria: 3 },
        { nombre: 'Muebles de Oficina', idcategoria_categoria: 3 },
        { nombre: 'Alfombras y Bajadas de Cama', idcategoria_categoria: 3 },
        { nombre: 'Espejos', idcategoria_categoria: 3 },
        { nombre: 'Almohadas, Cojines y Fundas', idcategoria_categoria: 3 },
        { nombre: 'Relojes', idcategoria_categoria: 3 },
        { nombre: 'Artículos de Decoración', idcategoria_categoria: 3 },
        { nombre: 'Dispensadores', idcategoria_categoria: 3 },
        { nombre: 'Camas', idcategoria_categoria: 3 },
        { nombre: 'Camarotes', idcategoria_categoria: 3 },
        { nombre: 'Camas para Niños y Cunas', idcategoria_categoria: 3 },
        { nombre: 'Colchones', idcategoria_categoria: 3 },
        { nombre: 'Respaldos', idcategoria_categoria: 3 },
        { nombre: 'Ropa de Cama', idcategoria_categoria: 3 },
        { nombre: 'Ropa de Cuna', idcategoria_categoria: 3 },
        { nombre: 'Mesas de Comedor y de Living', idcategoria_categoria: 3 },
        { nombre: 'Comedores', idcategoria_categoria: 3 },
        { nombre: 'Muebles de Terraza y Balcón', idcategoria_categoria: 3 },
        { nombre: 'Artículos de Jardinería', idcategoria_categoria: 3 },
        { nombre: 'Motosierras y Podadoras', idcategoria_categoria: 3 },
        { nombre: 'Corta Césped y Orilladoras', idcategoria_categoria: 3 },
        { nombre: 'Tractores para Césped', idcategoria_categoria: 3 },
        { nombre: 'Artículos para Cortar Césped', idcategoria_categoria: 3 },
        { nombre: 'Basureros', idcategoria_categoria: 3 },
        { nombre: 'Deshodorante ambiental', idcategoria_categoria: 3 },
        { nombre: 'Living', idcategoria_categoria: 3 },
        { nombre: 'Poltronas', idcategoria_categoria: 3 },
        { nombre: 'Sillones', idcategoria_categoria: 3 },
        { nombre: 'Sillas', idcategoria_categoria: 3 },
        { nombre: 'Banquetas y Pouf', idcategoria_categoria: 3 },
        { nombre: 'Lámparas', idcategoria_categoria: 3 },
        { nombre: 'Focos', idcategoria_categoria: 3 },
        { nombre: 'Ampolletas', idcategoria_categoria: 3 }
    ])
    
    tablaSubcategoria.bulkCreate([
        { nombre: 'Tops', idcategoria_categoria: 4 },
        { nombre: 'Blusas', idcategoria_categoria: 4 },
        { nombre: 'Poleras', idcategoria_categoria: 4 },
        { nombre: 'Camisas', idcategoria_categoria: 4 },
        { nombre: 'Polerones', idcategoria_categoria: 4 },
        { nombre: 'Parkas, Chaquetas y Abrigos', idcategoria_categoria: 4 },
        { nombre: 'Trajes y Ternos', idcategoria_categoria: 4 },
        { nombre: 'Pantalones, Jeans y Buzos', idcategoria_categoria: 4 },
        { nombre: 'Enteritos y Jardineras', idcategoria_categoria: 4 },
        { nombre: 'Vestidos', idcategoria_categoria: 4 },
        { nombre: 'Faldas', idcategoria_categoria: 4 },
        { nombre: 'Shorts', idcategoria_categoria: 4 },
        { nombre: 'Trajes de Baño', idcategoria_categoria: 4 },
        { nombre: 'Ropa Deportiva', idcategoria_categoria: 4 },
        { nombre: 'Ropa para Niños y Bebés', idcategoria_categoria: 4 },
        { nombre: 'Ropa de abrigo', idcategoria_categoria: 4 },
        { nombre: 'Ropa para dormir y para estar en casa', idcategoria_categoria: 4 },
        { nombre: 'Relojes Análogos y Digitales', idcategoria_categoria: 4 },
        { nombre: 'Joyas', idcategoria_categoria: 4 },
        { nombre: 'Lentes de Sol', idcategoria_categoria: 4 },
        { nombre: 'Lentes Ópticos', idcategoria_categoria: 4 },
        { nombre: 'Carteras', idcategoria_categoria: 4 },
        { nombre: 'Billeteras', idcategoria_categoria: 4 },
        { nombre: 'Gorros y Jockey', idcategoria_categoria: 4 },
        { nombre: 'Bufandas, Pañuelos y Bandanas', idcategoria_categoria: 4 },
        { nombre: 'Guantes y Mitones', idcategoria_categoria: 4 },
        { nombre: 'Cinturones', idcategoria_categoria: 4 },
        { nombre: 'Corbatas y Corbatines', idcategoria_categoria: 4 },
        { nombre: 'Paraguas', idcategoria_categoria: 4 },
        { nombre: 'Llaveros', idcategoria_categoria: 4 },
        { nombre: 'Calzado Mujer', idcategoria_categoria: 4 },
        { nombre: 'Calzado Hombre', idcategoria_categoria: 4 },
        { nombre: 'Calzado Niña', idcategoria_categoria: 4 },
        { nombre: 'Calzado Niño', idcategoria_categoria: 4 },
        { nombre: 'Ropa Interior', idcategoria_categoria: 4 },
        { nombre: 'Calcetines', idcategoria_categoria: 4 },
        { nombre: 'Pijamas', idcategoria_categoria: 4 }
    ])

    tablaSubcategoria.bulkCreate([
        { nombre: 'Afeitado y arreglo personal', idcategoria_categoria: 5 },
        { nombre: 'Ayudas para conciliar el sueño', idcategoria_categoria: 5 },
        { nombre: 'Cosméticos', idcategoria_categoria: 5 },
        { nombre: 'Cuidado bucal', idcategoria_categoria: 5 },
        { nombre: 'Cuidado capilar', idcategoria_categoria: 5 },
        { nombre: 'Masaje y relajación', idcategoria_categoria: 5 },
        { nombre: 'Productos sanitarios femeninos', idcategoria_categoria: 5 },
        { nombre: 'Alisadores y Cepillos eléctricos', idcategoria_categoria: 5 }
    ])

    tablaSubcategoria.bulkCreate([
        { nombre: 'Camping y senderismo', idcategoria_categoria: 6 },
        { nombre: 'Ciclismo', idcategoria_categoria: 6 },
        { nombre: 'Deportes acuáticos y navegación deportiva', idcategoria_categoria: 6 },
        { nombre: 'Patinaje sobre ruedas y en línea', idcategoria_categoria: 6 },
        { nombre: 'Pesca', idcategoria_categoria: 6 },
        { nombre: 'Skateboard y snowboard', idcategoria_categoria: 6 },
        { nombre: 'Scooters', idcategoria_categoria: 6 },
        { nombre: 'Boxeo y artes marciales', idcategoria_categoria: 6 },
        { nombre: 'Fútbol', idcategoria_categoria: 6 },
        { nombre: 'Rugby', idcategoria_categoria: 6 },
        { nombre: 'Pesas', idcategoria_categoria: 6 },
        { nombre: 'Cardio', idcategoria_categoria: 6 },
        { nombre: 'Yoga y pilates', idcategoria_categoria: 6 },
        { nombre: 'Juegos de interior', idcategoria_categoria: 6 },
        { nombre: 'Ping pong', idcategoria_categoria: 6 },
        { nombre: 'Taca Taca', idcategoria_categoria: 6 },
        { nombre: 'Indumentaria Moto Cross/Enduro', idcategoria_categoria: 6 },
        { nombre: 'Tenis y Padel', idcategoria_categoria: 6 },
        { nombre: 'Basquetbol', idcategoria_categoria: 6 },
        { nombre: 'Termos, mugs y botellas', idcategoria_categoria: 6 },
        { nombre: 'Voleibol y Handball', idcategoria_categoria: 6 }
    ])

    tablaSubcategoria.bulkCreate([
        { nombre: 'Bebidas y licores', idcategoria_categoria: 7 },
        { nombre: 'Carnes y pescados', idcategoria_categoria: 7 },
        { nombre: 'Frutas y verduras', idcategoria_categoria: 7 },
        { nombre: 'Frescos y lácteos', idcategoria_categoria: 7 },
        { nombre: 'Congelados', idcategoria_categoria: 7 },
        { nombre: 'Abarrotes', idcategoria_categoria: 7 },
        { nombre: 'Panaderia y pastelería', idcategoria_categoria: 7 },
        { nombre: 'Limpieza y aseo', idcategoria_categoria: 7 },
        { nombre: 'Cotillón y festividades', idcategoria_categoria: 7 },
        { nombre: 'Disfraces', idcategoria_categoria: 7 },
    ])

    tablaSubcategoria.bulkCreate([
        {nombre: 'Productos químicos', idcategoria_categoria: 8},
        {nombre: 'Cadenas, alambre y cuerda', idcategoria_categoria: 8},
        {nombre: 'Seguridad y prevención', idcategoria_categoria: 8},
        {nombre: 'Alicates', idcategoria_categoria: 8},
        {nombre: 'Clavadoras y grapadoras', idcategoria_categoria: 8},
        {nombre: 'Destornilladores', idcategoria_categoria: 8},
        {nombre: 'Soldadoras', idcategoria_categoria: 8},
        {nombre: 'Fresadoras', idcategoria_categoria: 8},
        {nombre: 'Esmeriles', idcategoria_categoria: 8},
        {nombre: 'Otras herramientas', idcategoria_categoria: 8},
        {nombre: 'Herramientas de pintura', idcategoria_categoria: 8},
        {nombre: 'Lijadoras', idcategoria_categoria: 8},
        {nombre: 'Dados y llaves', idcategoria_categoria: 8},
        {nombre: 'Martillos y mazos', idcategoria_categoria: 8},
        {nombre: 'Pulidoras', idcategoria_categoria: 8},
        {nombre: 'Sierras', idcategoria_categoria: 8},
        {nombre: 'Sopletes', idcategoria_categoria: 8},
        {nombre: 'Taladros', idcategoria_categoria: 8},
        {nombre: 'Hidrolavadoras', idcategoria_categoria: 8},
        {nombre: 'Tornos', idcategoria_categoria: 8},
        {nombre: 'Escaleras', idcategoria_categoria: 8},
        {nombre: 'Baterías y Cargadores', idcategoria_categoria: 8},
        {nombre: 'Motores y generadores', idcategoria_categoria: 8},
        {nombre: 'Candados y pestillos', idcategoria_categoria: 8},
        {nombre: 'Materiales de construcción', idcategoria_categoria: 8},
        {nombre: 'Suministros eléctricos', idcategoria_categoria: 8},
        {nombre: 'Cables eléctricos', idcategoria_categoria: 8}
    ])

    tablaSubcategoria.bulkCreate([
        { nombre: 'Baño de bebés', idcategoria_categoria: 9 },
        { nombre: 'Juguetes y actividades para bebés', idcategoria_categoria: 9 },
        { nombre: 'Mecedoras y sillas para bebés', idcategoria_categoria: 9 },
        { nombre: 'Lactancia y alimentación', idcategoria_categoria: 9 },
        { nombre: 'Pañales', idcategoria_categoria: 9 },
        { nombre: 'Coches', idcategoria_categoria: 9 },
        { nombre: 'Sillas para autos', idcategoria_categoria: 9 },
    ])

    tablaSubcategoria.bulkCreate([
        { nombre: 'Juegos de mesa', idcategoria_categoria: 10 },
        { nombre: 'Juguetes', idcategoria_categoria: 10 },
        { nombre: 'Alimento Mascotas', idcategoria_categoria: 11 },
        { nombre: 'Casas y Accesorios', idcategoria_categoria: 11 },
    ])

    tablaSubcategoria.bulkCreate([
        { nombre: 'Instrumentos de cuerda', idcategoria_categoria: 12 },
        { nombre: 'Instrumentos de viento', idcategoria_categoria: 12 },
        { nombre: 'Instrumentos de percusión', idcategoria_categoria: 12 },
        { nombre: 'Accesorios musicales', idcategoria_categoria: 12 },
        { nombre: 'Pianos y sintetizadores', idcategoria_categoria: 12 },
        { nombre: 'Accesorios para vehículos', idcategoria_categoria: 13 },
        { nombre: 'Piezas para vehículos', idcategoria_categoria: 13 },
        { nombre: 'Neumáticos', idcategoria_categoria: 13 },
        { nombre: 'Vehículos', idcategoria_categoria: 13 }
    ])

    tablaUsuario.create({
        nombre: 'ADMIN',
        apellido: 'ADMIN',
        correo: 'admin@mail.com',
        contrasena: '123456789',
        admin: 1
    })
    
}